package(default_visibility = ["//visibility:public"])

java_test(
    name = "CoffeeScriptCompilerTest",
    srcs = ["CoffeeScriptCompilerTest.java"],
    deps = [
        "//src/main/java/io/cong/chen/coffeescriptcompiler:coffee_script_compiler",
    ],
)
